apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnssd-service-instances.proclaim.dogmatiq.io
  labels:
    {{- include "proclaim.labels" . | nindent 4 }}
spec:
  scope: Namespaced
  group: proclaim.dogmatiq.io
  names:
    plural: dnssd-service-instances
    singular: dnssd-service-instance
    kind: DNSSDServiceInstance
    categories:
      - dnssd
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - instance
              properties:
                instance:
                  description: The DNS-SD service instance to advertise.
                  type: object
                  required:
                    - name
                    - serviceType
                    - domain
                  properties:
                    name:
                      description: A unique name for this particular instance of the service.
                      type: string
                      x-kubernetes-validations:
                        - message: instance name is immutable
                          rule: self == oldSelf
                    serviceType:
                      description: The type of service to advertise, e.g. "_http._tcp".
                      type: string
                      x-kubernetes-validations:
                        - message: service type is immutable
                          rule: self == oldSelf
                    domain:
                      description: The domain on which the service is advertised.
                      type: string
                      x-kubernetes-validations:
                        - message: domain is immutable
                          rule: self == oldSelf
                    ttl:
                      description: The time-to-live of the instance's DNS records.
                      type: string
                      format: duration
                      default: "60s"
                    targets:
                      description: A list of addresses at which the service can be reached.
                      type: array
                      minItems: 1
                      maxItems: 1
                      items:
                        type: object
                        required:
                          - host
                          - port
                        properties:
                          host:
                            description: The host name at which the service can be reached.
                            type: string
                          port:
                            description: The port number at which the service can be reached.
                            type: integer
                            format: uint16
                          priority:
                            description: The priority of the target's SRV record.
                            type: integer
                            format: uint16
                            default: 0
                          weight:
                            description: The weight of the target's SRV record.
                            type: integer
                            format: uint16
                            default: 0
                    attributes:
                      description: An array of attribute sets. Each item in the array corresponds to a separate TXT record.
                      type: array
                      items:
                        description: A map of attribute name to value. Values can be any scalar value; boolean values are treated as "flags".
                        type: object
                        additionalProperties: true

            status:
              type: object
              properties:
                provider:
                  description: The internal ID of the DNS provider that is advertising the DNS-SD service instance.
                  type: string
                providerDescription:
                  description: A human-readable description of the DNS provider that is advertising the DNS-SD service instance.
                  type: string
                  default: Unknown
                advertiser:
                  description: A provider-specific structure identifying the advertiser.
                  type: object
                  additionalProperties: true
                conditions:
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - type
                  description: List of conditions to indicate the status of the DNS-SD service instance.
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      type:
                        description: Type of the condition.
                        type: string
                      status:
                        description: Status of the condition.
                        type: string
                        enum:
                          - "Unknown"
                          - "True"
                          - "False"
                      reason:
                        description: A machine-readable explanation for the condition's last transition.
                        type: string
                      message:
                        description: A human-readable description that complements the reason.
                        type: string
                      observedGeneration:
                        description: The generation of the DNS-SD resource that was known to the controller when this condition was set.
                        type: integer
                        format: int64
                      lastTransitionTime:
                        description: The time at which this condition was last changed.
                        type: string
                        format: date-time

      additionalPrinterColumns:
        - name: Instance Name
          description: The name of the DNS-SD instance to advertise.
          type: string
          jsonPath: .spec.instance.name
        - name: Service Type
          description: The type of service that the instance provides.
          type: string
          jsonPath: .spec.instance.serviceType
        - name: Domain
          description: The domain name under which the DNS records are created.
          type: string
          jsonPath: .spec.instance.domain
        - name: Host
          description: The host name at which the service can be reached.
          type: string
          jsonPath: .spec.instance.targets[0].host
        - name: Port
          description: The port number at which the service can be reached.
          type: integer
          jsonPath: .spec.instance.targets[0].port
        - name: Provider
          description: The provider used to publish the DNS records.
          type: string
          jsonPath: .status.providerDescription
        - name: Ready
          description: Indicates whether the DNS records are in sync with the desired state.
          type: string
          jsonPath: .status.conditions[?(@.type=="Discoverable")].status
        - name: Reason
          description: The reason for the current ready status.
          type: string
          jsonPath: .status.conditions[?(@.type=="Discoverable")].reason
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
