apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "proclaim.fullname" . }}
  labels:
    {{- include "proclaim.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.common.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.rbac.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - proclaim.dogmatiq.io
    resources:
      - dnssd-service-instances
      - dnssd-service-instances/status
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
